name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Corre todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: AndresContreras1034
          outputs: |
            ./github-user-contribution.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
          add: "github-user-contribution.svg"
