name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Corre todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake animation
        uses: Platane/snk@master
        with:
          github_user_name: AndresContreras1034
          outputs: |
            dist/github-user-contribution.svg

      - name: Push the snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

